#!/usr/bin/env bash
# ── Hyperlight JS × GitHub Copilot CLI Demo ─────────────────────────
#
# "Open the pod bay doors, HAL." — 2001: A Space Odyssey (1968)
# ... except this sandbox actually listens when you tell it to stop.
#
# This script demonstrates using the Hyperlight JS MCP server with
# GitHub Copilot CLI. It:
#   1. Verifies prerequisites (Copilot CLI + Node.js + built guest)
#   2. Configures the MCP server (persistent or session-only)
#   3. Runs example prompts via Copilot CLI programmatic mode
#
# Usage:
#   ./demo-copilot-cli.sh              # Interactive — walks you through it
#   ./demo-copilot-cli.sh --headless   # Non-interactive — runs all demos
#   ./demo-copilot-cli.sh --prompt "Calculate pi to 50 digits"  # Run a single prompt
#   ./demo-copilot-cli.sh --install    # Install MCP config permanently
#   ./demo-copilot-cli.sh --uninstall  # Remove MCP config
#   ./demo-copilot-cli.sh --model gpt-4o  # Use a specific model
#   ./demo-copilot-cli.sh --cpu-timeout 2000 --heap-size 32  # Custom limits
#
# Options:
#   --model <name>          LLM model to use (default: claude-opus-4.6)
#   --show-code             Display the JavaScript code generated by the model
#   --show-command          Display the copilot CLI command line being executed
#   --prompt <text>         Run a single custom prompt instead of built-in demos
#   --cpu-timeout <ms>      CPU time limit per execution (default: 1000)
#   --wall-timeout <ms>     Wall-clock backstop per execution (default: 5000)
#   --heap-size <MB>        Guest heap size in megabytes (default: 16)
#   --scratch-size <MB>       Guest scratch size in megabytes (default: 1)
#
# ─────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Colours & Formatting ────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
RESET='\033[0m'

# ── Defaults ─────────────────────────────────────────────────────────
# "These go to eleven." — Spinal Tap (1984)
DEFAULT_MODEL="claude-opus-4.6"
MODEL="${DEFAULT_MODEL}"
SHOW_CODE=false
SHOW_COMMAND=false
CUSTOM_PROMPT=""

# Sandbox limits — can be overridden via CLI flags or env vars.
# CLI flags take precedence over env vars, env vars over defaults.
CPU_TIMEOUT="${HYPERLIGHT_CPU_TIMEOUT_MS:-1000}"
WALL_TIMEOUT="${HYPERLIGHT_WALL_TIMEOUT_MS:-5000}"
HEAP_SIZE="${HYPERLIGHT_HEAP_SIZE_MB:-16}"
SCRATCH_SIZE="${HYPERLIGHT_SCRATCH_SIZE_MB:-1}"

# ── Paths ────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVER_JS="${SCRIPT_DIR}/server.js"
COPILOT_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.copilot}"
MCP_CONFIG_FILE="${COPILOT_CONFIG_DIR}/mcp-config.json"
MCP_SERVER_NAME="hyperlight-sandbox"

# ── Helpers ──────────────────────────────────────────────────────────

info()  { echo -e "${CYAN}ℹ${RESET}  $*"; }
ok()    { echo -e "${GREEN}✅${RESET} $*"; }
warn()  { echo -e "${YELLOW}⚠${RESET}  $*"; }
fail()  { echo -e "${RED}❌${RESET} $*" >&2; exit 1; }

banner() {
    echo ""
    echo -e "${BOLD}${CYAN}🔒 Hyperlight JS × GitHub Copilot CLI Demo${RESET}"
    echo ""
}

separator() {
    echo -e "${DIM}\n────────────────────────────────────────────────────────${RESET}\n"
}

# Timing helpers — because "Time... is not on my side" — The Rolling Stones (1964, close enough)
# Uses millisecond precision when available; falls back to portable options on macOS/BSD.
now_ms() {
    # Prefer GNU date if available (system date or gdate), and verify output is numeric.
    if date +%s%3N 2>/dev/null | grep -Eq '^[0-9]+$'; then
        date +%s%3N
    elif command -v gdate >/dev/null 2>&1; then
        gdate +%s%3N
    elif command -v python3 >/dev/null 2>&1; then
        python3 - <<'EOF'
import time, sys
sys.stdout.write(str(int(time.time() * 1000)))
EOF
    elif command -v node >/dev/null 2>&1; then
        node -e 'console.log(Date.now())'
    else
        # Portable fallback: seconds since epoch with millisecond field set to 000.
        date +%s000
    fi
}

# Log elapsed time since a given start timestamp (ms)
# Usage: log_elapsed "phase description" "$start_ms"
log_elapsed() {
    local phase="$1"
    local start="$2"
    local end
    end="$(now_ms)"
    local elapsed_ms=$(( end - start ))
    local elapsed_s elapsed_frac
    elapsed_s=$(( elapsed_ms / 1000 ))
    elapsed_frac=$(( elapsed_ms % 1000 ))
    printf "${DIM}⏱  %-40s %d.%03ds${RESET}\n" "${phase}" "${elapsed_s}" "${elapsed_frac}"
}

# ── Prerequisite Checks ─────────────────────────────────────────────

check_prerequisites() {
    info "Checking prerequisites..."

    # Node.js
    if ! command -v node &>/dev/null; then
        fail "Node.js is required but not installed. Install from https://nodejs.org"
    fi
    ok "Node.js $(node --version)"

    # Copilot CLI
    if command -v copilot &>/dev/null; then
        COPILOT_BIN="copilot"
    elif [[ -x "${HOME}/.vscode-server/data/User/globalStorage/github.copilot-chat/copilotCli/copilot" ]]; then
        COPILOT_BIN="${HOME}/.vscode-server/data/User/globalStorage/github.copilot-chat/copilotCli/copilot"
    else
        fail "GitHub Copilot CLI not found. Install with: npm install -g @github/copilot"
    fi
    ok "Copilot CLI found at: ${COPILOT_BIN}"

    # Server script
    if [[ ! -f "${SERVER_JS}" ]]; then
        fail "Server script not found at: ${SERVER_JS}"
    fi
    ok "MCP server: ${SERVER_JS}"

    # npm dependencies
    if [[ ! -d "${SCRIPT_DIR}/node_modules" ]]; then
        warn "node_modules not found — installing dependencies..."
        (cd "${SCRIPT_DIR}" && npm install) || fail "npm install failed"
    fi
    ok "Dependencies installed"

    # Native addon smoke test — verify the .node binary loads and has
    # the methods we need. The old check started server.js and waited
    # for a banner that never came (stdio transport blocks on connect).
    # This just imports lib.js which validates the native addon at
    # module load time. Instant, reliable, catches the exact failure.
    # "Trust, but verify." — Reagan (1987)
    info "Verifying native addon loads correctly..."
    local lib_js="${SCRIPT_DIR}/../../lib.js"
    local smoke_err
    if ! smoke_err="$(node --input-type=module -e "import('${lib_js}').then(() => console.log('OK')).catch(e => { console.error(e.message); process.exit(1); })" 2>&1)"; then
        fail "Native addon failed to load — rebuild with 'just build'.\n${smoke_err}"
    fi
    ok "Native addon loads successfully"

    echo ""
}

# ── MCP Config Management ───────────────────────────────────────────

# Build the JSON config for this MCP server.
# Passes HYPERLIGHT_TIMING_LOG and HYPERLIGHT_CODE_LOG via the env
# field so the Copilot CLI-spawned server process receives them —
# environment inheritance doesn't work because Copilot CLI is the
# parent process, not our shell.
build_mcp_json() {
    # Forward sandbox configuration + observability env vars to the
    # MCP server process. Copilot CLI spawns the server itself, so
    # normal env inheritance from our shell doesn't apply — we must
    # embed them in the MCP config's "env" field.
    local install_mode="${1:-}"

    export HYPERLIGHT_CPU_TIMEOUT_MS="${CPU_TIMEOUT}"
    export HYPERLIGHT_WALL_TIMEOUT_MS="${WALL_TIMEOUT}"
    export HYPERLIGHT_HEAP_SIZE_MB="${HEAP_SIZE}"
    export HYPERLIGHT_SCRATCH_SIZE_MB="${SCRATCH_SIZE}"

    node -e "
        const installMode = '${install_mode}' === 'install';
        const env = {
            HYPERLIGHT_CPU_TIMEOUT_MS:  process.env.HYPERLIGHT_CPU_TIMEOUT_MS,
            HYPERLIGHT_WALL_TIMEOUT_MS: process.env.HYPERLIGHT_WALL_TIMEOUT_MS,
            HYPERLIGHT_HEAP_SIZE_MB:    process.env.HYPERLIGHT_HEAP_SIZE_MB,
            HYPERLIGHT_SCRATCH_SIZE_MB:   process.env.HYPERLIGHT_SCRATCH_SIZE_MB,
        };
        if (installMode) {
            // Permanent install: include timing log at a fixed well-known path.
            // Code logging is intentionally omitted — it would persist all
            // executed JS to disk by default (privacy concern, unbounded growth).
            env.HYPERLIGHT_TIMING_LOG = '/tmp/hyperlight-timing.jsonl';
        } else {
            if (process.env.HYPERLIGHT_TIMING_LOG) env.HYPERLIGHT_TIMING_LOG = process.env.HYPERLIGHT_TIMING_LOG;
            if (process.env.HYPERLIGHT_CODE_LOG)   env.HYPERLIGHT_CODE_LOG   = process.env.HYPERLIGHT_CODE_LOG;
        }

        const server = {
            type: 'stdio',
            command: 'node',
            args: ['${SERVER_JS}'],
            env,
        };

        console.log(JSON.stringify({ mcpServers: { '${MCP_SERVER_NAME}': server } }, null, 4));
    "
}

# Install config permanently into ~/.copilot/mcp-config.json
install_mcp_config() {
    info "Installing MCP server config to ${MCP_CONFIG_FILE}..."
    mkdir -p "${COPILOT_CONFIG_DIR}"

    if [[ -f "${MCP_CONFIG_FILE}" ]]; then
        # Check if already configured
        if grep -q "${MCP_SERVER_NAME}" "${MCP_CONFIG_FILE}" 2>/dev/null; then
            ok "Already configured in ${MCP_CONFIG_FILE}"
            return 0
        fi

        # Backup existing config
        cp "${MCP_CONFIG_FILE}" "${MCP_CONFIG_FILE}.bak"
        warn "Backed up existing config to ${MCP_CONFIG_FILE}.bak"

        # Merge: add our server to existing mcpServers with full env
        # block including fixed log paths for the permanent install.
        # Use node for reliable JSON merging.
        node -e "
            const fs = require('fs');
            const existing = JSON.parse(fs.readFileSync('${MCP_CONFIG_FILE}.bak', 'utf8'));
            existing.mcpServers = existing.mcpServers || {};
            existing.mcpServers['${MCP_SERVER_NAME}'] = {
                type: 'stdio',
                command: 'node',
                args: ['${SERVER_JS}'],
                env: {
                    HYPERLIGHT_CPU_TIMEOUT_MS:  '${CPU_TIMEOUT}',
                    HYPERLIGHT_WALL_TIMEOUT_MS: '${WALL_TIMEOUT}',
                    HYPERLIGHT_HEAP_SIZE_MB:    '${HEAP_SIZE}',
                    HYPERLIGHT_SCRATCH_SIZE_MB:   '${SCRATCH_SIZE}',
                    HYPERLIGHT_TIMING_LOG:      '/tmp/hyperlight-timing.jsonl',
                },
            };
            fs.writeFileSync('${MCP_CONFIG_FILE}', JSON.stringify(existing, null, 4) + '\n');
        "
    else
        build_mcp_json install > "${MCP_CONFIG_FILE}"
    fi

    ok "Installed! Config written to ${MCP_CONFIG_FILE}"
    echo -e "${DIM}$(cat "${MCP_CONFIG_FILE}")${RESET}"
}

# Remove our server from the config
uninstall_mcp_config() {
    if [[ ! -f "${MCP_CONFIG_FILE}" ]]; then
        warn "No config file found at ${MCP_CONFIG_FILE}"
        return 0
    fi

    if ! grep -q "${MCP_SERVER_NAME}" "${MCP_CONFIG_FILE}" 2>/dev/null; then
        warn "${MCP_SERVER_NAME} not found in ${MCP_CONFIG_FILE}"
        return 0
    fi

    node -e "
        const fs = require('fs');
        const config = JSON.parse(fs.readFileSync('${MCP_CONFIG_FILE}', 'utf8'));
        delete config.mcpServers?.['${MCP_SERVER_NAME}'];
        if (Object.keys(config.mcpServers || {}).length === 0) {
            fs.unlinkSync('${MCP_CONFIG_FILE}');
            console.log('Config file removed (no servers remaining).');
        } else {
            fs.writeFileSync('${MCP_CONFIG_FILE}', JSON.stringify(config, null, 4) + '\n');
            console.log('Server removed from config.');
        }
    "
    ok "Uninstalled ${MCP_SERVER_NAME} from Copilot CLI config"
}

# Warn if a permanent install exists — the script's per-session
# --additional-mcp-config will override it for the duration of the
# session. Same server name = temp config wins via augment merge
# semantics. "Danger, Will Robinson!" — Lost in Space (syndicated
# throughout the 80s)
check_config_conflict() {
    if [[ -f "${MCP_CONFIG_FILE}" ]] && grep -q "${MCP_SERVER_NAME}" "${MCP_CONFIG_FILE}" 2>/dev/null; then
        warn "A permanent install of '${MCP_SERVER_NAME}' exists in ${MCP_CONFIG_FILE}."
        warn "The script's per-session config (--additional-mcp-config) will override it."
        warn "To use the permanent config directly, just run: copilot"
    fi
}

# ── Demo Prompts ─────────────────────────────────────────────────────

# Array of demo prompts — each is [title, prompt]
DEMO_PROMPTS=(
    "Calculate π to 50 decimal places"
    "Write a function using the Machin formula to calculate π to 50 decimal places. Return the result as a JSON object with the value as a string."

    "Sieve of Eratosthenes"
    "Find all prime numbers below 10,000 using the Sieve of Eratosthenes. Return JSON with the count and the last 10 primes."

    "Maze Generation"
    "Generate a random 25×25 maze using recursive backtracking. Return it as ASCII art using # for walls and spaces for paths, plus the dimensions as JSON."
)
DEMO_COUNT=$(( ${#DEMO_PROMPTS[@]} / 2 ))

# Run a single prompt via Copilot CLI programmatic mode
run_prompt() {
    local title="$1"
    local prompt="$2"
    local prompt_start
    prompt_start="$(now_ms)"

    echo -e "${BOLD}🎯 ${title}${RESET}"
    echo -e "${DIM}Prompt: ${prompt}${RESET}"
    echo -e "${DIM}Model:  ${MODEL}${RESET}"

    # Flags rationale (from `copilot --help`):
    #
    #   --additional-mcp-config @file   Register our MCP server for this session
    #                                   only (no permanent install required).
    #
    #   --allow-all-tools               REQUIRED for -p (non-interactive) mode.
    #                                   Individual --allow-tool patterns only work
    #                                   in interactive mode's permission prompts.
    #                                   See `copilot --help` for details.
    #
    #   --available-tools               Restrict model to ONLY our MCP tool plus
    #                                   internal tools the agent needs to function
    #                                   (task_complete, report_intent). The model
    #                                   cannot call shell, file write, web fetch,
    #                                   or any other tool. This is the security
    #                                   layer — even though --allow-all-tools is
    #                                   set, only whitelisted tools are visible.
    #
    #   --no-custom-instructions        Don't load AGENTS.md / copilot-instructions.md
    #                                   which could confuse the agent.
    #
    #   --no-ask-user                   Don't ask clarifying questions in -p mode.
    #
    #   --disable-builtin-mcps          Don't load the GitHub MCP server — we only
    #                                   want our sandbox.
    #
    #   -p                              Programmatic (non-interactive) mode.
    #
    # Write MCP config to a temp file — the --additional-mcp-config
    # flag accepts a file path when prefixed with @.
    # Timing log file — the MCP server writes a JSON-lines record here
    # each time execute_javascript is called. We read it afterwards to
    # show a model-vs-tool breakdown. Like Knight Rider's KITT dashboard
    # but for sandbox performance.
    #
    # Must be set BEFORE build_mcp_json so the env field is included
    # in the MCP config (Copilot CLI spawns the server, not our shell,
    # so normal env inheritance doesn't apply).
    local timing_log
    timing_log="$(mktemp "${TMPDIR:-/tmp}/hyperlight-timing-XXXXXX.jsonl")"
    export HYPERLIGHT_TIMING_LOG="${timing_log}"

    # Code log — the MCP server dumps the received JS source here
    local code_log=""
    if [[ "${SHOW_CODE}" == true ]]; then
        code_log="$(mktemp "${TMPDIR:-/tmp}/hyperlight-code-XXXXXX.js")"
        export HYPERLIGHT_CODE_LOG="${code_log}"
    else
        unset HYPERLIGHT_CODE_LOG 2>/dev/null || true
    fi

    local mcp_tmp
    mcp_tmp="$(mktemp "${TMPDIR:-/tmp}/hyperlight-mcp-XXXXXX.json")"
    build_mcp_json > "${mcp_tmp}"

    # shellcheck disable=SC2064
    trap "rm -f '${mcp_tmp}' '${timing_log}' '${code_log:-}'" RETURN

    # The prompt is deliberately structured to steer the agent:
    #   1. Lead with the task — what JS code to write
    #   2. Explicitly name the tool to call
    #   3. Remind it the code must use `return` to produce output
    #   4. Tell it NOT to read files, start servers, or use shell
    #
    # This avoids the "Full Metal Jacket" problem where the agent
    # goes on a recon mission reading every file in the repo instead
    # of just calling the damn tool.
    local full_prompt
    full_prompt="TASK: ${prompt}

INSTRUCTIONS: You have an MCP tool called 'execute_javascript' from the 'hyperlight-sandbox' server. \
This tool takes a single parameter 'code' containing JavaScript source code. \
The code runs in a sandboxed QuickJS engine, NOT Node.js — there is no require(), no fetch(), no fs. \
The code MUST use 'return <expression>' at the top level to produce output (like a function body). \
Call the execute_javascript tool with your JavaScript code now. \
Do NOT read files, start servers, run shell commands, or do anything else. \
After you receive the tool result, present the answer in ONE short response and STOP. \
Do NOT attempt any follow-up actions, additional tool calls, or continuation. \
Your task is complete the moment you present the result."

    # Security: use the documented --allow-all-tools + --deny-tool pattern
    # from https://docs.github.com/copilot/concepts/agents/about-copilot-cli
    #
    #   --allow-all-tools : auto-approve all tools (required for -p mode)
    #   --deny-tool 'shell' : BLOCK all shell commands (takes precedence)
    #   --deny-tool 'write' : BLOCK all file write/edit operations
    #   --deny-tool 'read'  : BLOCK file reading (agent should only use our MCP tool)
    #   --deny-tool 'fetch' : BLOCK web/HTTP requests
    #   -s                  : Silent — agent response only, no stats/retry noise
    #
    # --deny-tool takes precedence over --allow-all-tools per the docs.
    # Internal plumbing tools (task_complete, report_intent) are NOT
    # in the shell/write/MCP categories so they remain available.
    # Our MCP tool (hyperlight-sandbox → execute_javascript) is allowed
    # because it's not denied.
    #
    # -s suppresses the agentic loop retry noise ("Continuing autonomously",
    # "Response was interrupted due to a server error") that occurs when
    # the model's continuation turn hits transient API errors after
    # already completing the actual task.
    #
    # We also filter out the "Execution failed" line that leaks through
    # -s when the agentic continuation gives up — the actual task was
    # already successful at that point. The exit code is still 0.
    #
    # Like WarGames taught us: the only winning move is not to grant
    # shell access.

    # “Show me the money!” — Jerry Maguire (1996... close enough to the 80s)
    if [[ "${SHOW_COMMAND}" == true ]]; then
        # Copy-pasteable command with the full structured prompt.
        # Uses double quotes for -p so single quotes in the prompt
        # don't need escaping. Omits --additional-mcp-config because
        # the temp file gets cleaned up. Relies on a permanent install.
        local mcp_installed=false
        if [[ -f "${MCP_CONFIG_FILE}" ]] && grep -q "${MCP_SERVER_NAME}" "${MCP_CONFIG_FILE}" 2>/dev/null; then
            mcp_installed=true
        fi

        # Build the install command with any non-default sandbox limits
        # so the permanent config gets the same settings.
        # "If you build it, he will come." — Field of Dreams (1989)
        local install_flags=""
        [[ "${CPU_TIMEOUT}"  != "1000" ]] && install_flags+=" --cpu-timeout ${CPU_TIMEOUT}"
        [[ "${WALL_TIMEOUT}" != "5000" ]] && install_flags+=" --wall-timeout ${WALL_TIMEOUT}"
        [[ "${HEAP_SIZE}"    != "16" ]]   && install_flags+=" --heap-size ${HEAP_SIZE}"
        [[ "${SCRATCH_SIZE}"   != "1" ]]    && install_flags+=" --scratch-size ${SCRATCH_SIZE}"

        echo ""
        echo -e "${CYAN}${BOLD}🔧 Copy-pasteable command:${RESET}"
        if [[ "${mcp_installed}" != true ]]; then
            echo ""
            echo -e "${YELLOW}⚠  The MCP server must be installed before this command will work.${RESET}"
            echo -e "${YELLOW}  Install it now:${RESET}"
            echo ""
            echo -e "${YELLOW}    ./demo-copilot-cli.sh --install${install_flags}${RESET}"
            echo ""
            echo -e "${YELLOW}  To remove it later:${RESET}"
            echo ""
            echo -e "${YELLOW}    ./demo-copilot-cli.sh --uninstall${RESET}"
        fi
        echo ""
        echo "  copilot \\"
        echo "    -p \"${full_prompt}\" \\"
        echo "    -s \\"
        echo "    --allow-all-tools \\"
        echo "    --deny-tool shell \\"
        echo "    --deny-tool write \\"
        echo "    --deny-tool read \\"
        echo "    --deny-tool fetch \\"
        echo "    --no-custom-instructions \\"
        echo "    --no-ask-user \\"
        echo "    --disable-builtin-mcps \\"
        echo "    --model ${MODEL}"
        echo ""
    fi

    local copilot_start
    copilot_start="$(now_ms)"

    # Pipe through two filters:
    #   1. Drop "Execution failed:" noise from agentic continuation retries
    #   2. Strip leading blank lines the CLI emits while waiting for the
    #      model — keeps blank lines *within* the response body intact.
    #      "Every breath you take, every blank you make…" — The Police (1983)
    "${COPILOT_BIN}" \
        -p "${full_prompt}" \
        -s \
        --additional-mcp-config "@${mcp_tmp}" \
        --allow-all-tools \
        --deny-tool 'shell' \
        --deny-tool 'write' \
        --deny-tool 'read' \
        --deny-tool 'fetch' \
        --no-custom-instructions \
        --no-ask-user \
        --disable-builtin-mcps \
        --model "${MODEL}" 2>&1 \
        | grep -v '^Execution failed:' \
        | awk 'NF{p=1} p' || {
            warn "Prompt failed (Copilot may not be authenticated or the model may be unavailable)"
            return 1
        }

    local copilot_elapsed_ms
    copilot_elapsed_ms=$(( $(now_ms) - copilot_start ))

    # ── Timing breakdown ──────────────────────────────────────────
    # Read the MCP server's timing log to split "model thinking" from
    # "tool execution". The server writes one JSON line per tool call.
    # ── Show generated code (if --show-code) ─────────────────────
    if [[ "${SHOW_CODE}" == true && -n "${code_log}" && -s "${code_log}" ]]; then
        echo -e "\n${BOLD}📝 Generated code:${RESET}"
        echo -e "${DIM}─────────────────────────────────────────────${RESET}"
        # Use sed to indent and dim each line for readability
        sed "s/^/  /" "${code_log}" | while IFS= read -r line; do
            echo -e "${DIM}${line}${RESET}"
        done
        echo -e "${DIM}─────────────────────────────────────────────${RESET}"
    fi

    echo -e "\n${BOLD}⏱  Timing breakdown:${RESET}"
    log_elapsed "Copilot CLI (total round-trip)" "${copilot_start}"

    if [[ -s "${timing_log}" ]]; then
        # Parse the last timing record (in case the model called the
        # tool more than once, the last call is the interesting one).
        # Single node invocation outputs space-separated values.
        local timing_values
        timing_values="$(tail -1 "${timing_log}" | node -e "
            process.stdin.resume();
            let d = '';
            process.stdin.on('data', c => d += c);
            process.stdin.on('end', () => {
                const t = JSON.parse(d);
                // Output: totalMs initMs setupMs compileMs snapshotMs executeMs
                console.log([t.totalMs, t.initMs, t.setupMs, t.compileMs, t.snapshotMs, t.executeMs].join(' '));
            });
        ")"

        # Read into individual variables
        local tool_total_ms tool_init_ms tool_setup_ms tool_compile_ms tool_snap_ms tool_exec_ms
        read -r tool_total_ms tool_init_ms tool_setup_ms tool_compile_ms tool_snap_ms tool_exec_ms <<< "${timing_values}"

        # Model time ≈ total copilot time minus tool time
        local model_ms=$(( copilot_elapsed_ms - tool_total_ms ))

        printf "  ${CYAN}%-38s${RESET} %d.%03ds  ${DIM}(LLM code generation + response)${RESET}\n" \
            "🤖 Model" "$(( model_ms / 1000 ))" "$(( model_ms % 1000 ))"
        printf "  ${CYAN}%-38s${RESET} %d.%03ds  ${DIM}(MCP tool total)${RESET}\n" \
            "🔧 Tool execution" "$(( tool_total_ms / 1000 ))" "$(( tool_total_ms % 1000 ))"

        # Sub-breakdown of tool time (indented)
        if (( tool_init_ms > 0 )); then
            printf "    ${DIM}├─ Sandbox init:     %5dms${RESET}\n" "${tool_init_ms}"
        fi
        printf "    ${DIM}├─ Handler setup:    %5dms${RESET}\n" "${tool_setup_ms}"
        printf "    ${DIM}├─ Compile & load:   %5dms${RESET}\n" "${tool_compile_ms}"
        printf "    ${DIM}├─ Snapshot:         %5dms${RESET}\n" "${tool_snap_ms}"
        printf "    ${DIM}└─ JS execution:     %5dms${RESET}\n" "${tool_exec_ms}"
    else
        warn "No tool timing data — the model may not have called the tool"
    fi

    log_elapsed "Total for '${title}'" "${prompt_start}"
}

# ── Main ─────────────────────────────────────────────────────────────

main() {
    # Parse arguments — extract --model before dispatching mode
    local mode="interactive"
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --model)
                if [[ -z "${2:-}" ]]; then
                    fail "--model requires a value (e.g. --model claude-opus-4.6)"
                fi
                MODEL="$2"
                shift 2
                ;;
            --show-code)
                SHOW_CODE=true
                shift
                ;;
            --show-command)
                SHOW_COMMAND=true
                shift
                ;;
            --prompt)
                if [[ -z "${2:-}" ]]; then fail "--prompt requires a value"; fi
                CUSTOM_PROMPT="$2"
                shift 2
                ;;
            --cpu-timeout)
                if [[ -z "${2:-}" ]]; then fail "--cpu-timeout requires a value in ms"; fi
                CPU_TIMEOUT="$2"
                shift 2
                ;;
            --wall-timeout)
                if [[ -z "${2:-}" ]]; then fail "--wall-timeout requires a value in ms"; fi
                WALL_TIMEOUT="$2"
                shift 2
                ;;
            --heap-size)
                if [[ -z "${2:-}" ]]; then fail "--heap-size requires a value in MB"; fi
                HEAP_SIZE="$2"
                shift 2
                ;;
            --scratch-size)
                if [[ -z "${2:-}" ]]; then fail "--scratch-size requires a value in MB"; fi
                SCRATCH_SIZE="$2"
                shift 2
                ;;
            --install|--uninstall|--headless)
                mode="$1"
                shift
                ;;
            *)
                fail "Unknown argument: $1\nUsage: $0 [--headless] [--install] [--uninstall] [--model <name>] [--prompt <text>] [--show-code] [--show-command] [--cpu-timeout <ms>] [--wall-timeout <ms>] [--heap-size <MB>] [--scratch-size <MB>]"
                ;;
        esac
    done

    banner
    info "Using model: ${BOLD}${MODEL}${RESET}"
    info "Sandbox limits: CPU ${BOLD}${CPU_TIMEOUT}ms${RESET}, wall ${BOLD}${WALL_TIMEOUT}ms${RESET}, heap ${BOLD}${HEAP_SIZE}MB${RESET}, scratch ${BOLD}${SCRATCH_SIZE}MB${RESET}"

    case "${mode}" in
        --install)
            check_prerequisites
            install_mcp_config
            echo ""
            info "You can now use it in Copilot CLI:"
            echo -e "  ${BOLD}copilot${RESET}"
            echo -e "  ${DIM}> Calculate π to 50 decimal places using the Machin formula${RESET}"
            exit 0
            ;;
        --uninstall)
            uninstall_mcp_config
            exit 0
            ;;
        --headless)
            check_prerequisites
            check_config_conflict

            # If a custom prompt was given, run just that one and exit.
            # "There can be only one." — Highlander (1986)
            if [[ -n "${CUSTOM_PROMPT}" ]]; then
                info "Running custom prompt in headless mode..."
                separator
                local run_start
                run_start="$(now_ms)"
                if run_prompt "Custom prompt" "${CUSTOM_PROMPT}"; then
                    separator
                    log_elapsed "Custom prompt" "${run_start}"
                    exit 0
                else
                    separator
                    log_elapsed "Custom prompt" "${run_start}"
                    exit 1
                fi
            fi

            info "Running ${DEMO_COUNT} demo prompts in headless mode..."
            separator

            local run_start
            run_start="$(now_ms)"
            local passed=0
            local failed=0

            for (( i=0; i<${#DEMO_PROMPTS[@]}; i+=2 )); do
                local title="${DEMO_PROMPTS[$i]}"
                local prompt="${DEMO_PROMPTS[$((i+1))]}"

                if run_prompt "${title}" "${prompt}"; then
                    passed=$((passed + 1))
                else
                    failed=$((failed + 1))
                fi
                separator
            done

            log_elapsed "All ${DEMO_COUNT} prompts" "${run_start}"
            echo -e "\n${BOLD}Results: ${GREEN}${passed} passed${RESET}"
            if (( failed > 0 )); then
                echo -e "         ${RED}${failed} failed${RESET}"
            fi
            exit "${failed}"
            ;;
        interactive|*)
            check_prerequisites
            check_config_conflict

            # Run the custom prompt first if one was provided
            if [[ -n "${CUSTOM_PROMPT}" ]]; then
                info "Running your custom prompt..."
                separator
                run_prompt "Custom prompt" "${CUSTOM_PROMPT}"
                separator
                info "Done! \"I'll be back.\" — The Terminator (1984)"
                exit 0
            fi

            info "This demo will run ${DEMO_COUNT} prompts through Copilot CLI,"
            info "each executing JavaScript inside a Hyperlight sandbox."
            echo ""
            info "The MCP server is configured per-session (no permanent install)."
            info "To install permanently, run: ${BOLD}$0 --install${RESET}"
            separator

            echo -e "${YELLOW}Ready to run demos?${RESET}"
            read -rp "Press Enter to continue (or Ctrl+C to cancel)... "
            echo ""

            for (( i=0; i<${#DEMO_PROMPTS[@]}; i+=2 )); do
                local title="${DEMO_PROMPTS[$i]}"
                local prompt="${DEMO_PROMPTS[$((i+1))]}"

                run_prompt "${title}" "${prompt}"
                separator

                if (( i + 2 < ${#DEMO_PROMPTS[@]} )); then
                    read -rp "Next demo? (Enter to continue, q to quit) " answer
                    if [[ "${answer}" == "q" ]]; then
                        info "Thanks for watching! \"I'll be back.\" — The Terminator (1984)"
                        exit 0
                    fi
                fi
            done

            echo -e "${GREEN}${BOLD}🎉 All demos complete!${RESET}"
            echo -e "${DIM}\"That's all, folks!\" — Porky Pig (well, 1930s, close enough)${RESET}"
            ;;
    esac
}

main "$@"
