#Requires -Version 7.0
<#
.SYNOPSIS
    Hyperlight JS × GitHub Copilot CLI Demo (PowerShell edition)

.DESCRIPTION
    "Open the pod bay doors, HAL." — 2001: A Space Odyssey (1968)
    ... except this sandbox actually listens when you tell it to stop.

    This script demonstrates using the Hyperlight JS MCP server with
    GitHub Copilot CLI. It:
      1. Verifies prerequisites (Copilot CLI + Node.js + built guest)
      2. Configures the MCP server (persistent or session-only)
      3. Runs example prompts via Copilot CLI programmatic mode

.PARAMETER Mode
    Operating mode: Interactive (default), Headless, Install, or Uninstall.

.PARAMETER Model
    LLM model to use (default: claude-opus-4.6).

.PARAMETER Prompt
    A custom prompt to run instead of the built-in demos. Runs the single
    prompt and exits (in both Headless and Interactive modes).

.PARAMETER ShowCode
    Display the JavaScript code generated by the model.

.PARAMETER ShowCommand
    Display the copilot CLI command line being executed. Useful for debugging
    or copying the command to run manually.

.PARAMETER CpuTimeout
    CPU time limit per execution in milliseconds (default: 1000).

.PARAMETER WallTimeout
    Wall-clock backstop per execution in milliseconds (default: 5000).

.PARAMETER HeapSize
    Guest heap size in megabytes (default: 16).

.PARAMETER ScratchSize
    Guest scratch size in megabytes (default: 1).

.EXAMPLE
    .\demo-copilot-cli.ps1
    # Interactive — walks you through it

.EXAMPLE
    .\demo-copilot-cli.ps1 -Mode Headless
    # Non-interactive — runs all demos

.EXAMPLE
    .\demo-copilot-cli.ps1 -Mode Install
    # Install MCP config permanently

.EXAMPLE
    .\demo-copilot-cli.ps1 -Model gpt-4o -Mode Headless
    # Use a specific model

.EXAMPLE
    .\demo-copilot-cli.ps1 -Prompt "Calculate the first 100 Fibonacci numbers" -Mode Headless
    # Run a single custom prompt

.EXAMPLE
    .\demo-copilot-cli.ps1 -ShowCommand -Mode Headless
    # Show the copilot CLI command being used

.EXAMPLE
    .\demo-copilot-cli.ps1 -CpuTimeout 2000 -HeapSize 32 -Mode Headless
    # Custom sandbox limits
#>

[CmdletBinding()]
param(
    [ValidateSet('Interactive', 'Headless', 'Install', 'Uninstall')]
    [string]$Mode = 'Interactive',

    [string]$Model = 'claude-opus-4.6',

    [string]$Prompt,

    [switch]$ShowCode,

    [switch]$ShowCommand,

    [ValidateRange(1, [int]::MaxValue)]
    [int]$CpuTimeout = $(if ($env:HYPERLIGHT_CPU_TIMEOUT_MS) { [int]$env:HYPERLIGHT_CPU_TIMEOUT_MS } else { 1000 }),

    [ValidateRange(1, [int]::MaxValue)]
    [int]$WallTimeout = $(if ($env:HYPERLIGHT_WALL_TIMEOUT_MS) { [int]$env:HYPERLIGHT_WALL_TIMEOUT_MS } else { 5000 }),

    [ValidateRange(1, [int]::MaxValue)]
    [int]$HeapSize = $(if ($env:HYPERLIGHT_HEAP_SIZE_MB) { [int]$env:HYPERLIGHT_HEAP_SIZE_MB } else { 16 }),

    [ValidateRange(1, [int]::MaxValue)]
    [int]$ScratchSize = $(if ($env:HYPERLIGHT_SCRATCH_SIZE_MB) { [int]$env:HYPERLIGHT_SCRATCH_SIZE_MB } else { 1 })
)

# ── Strict Mode ──────────────────────────────────────────────────────
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ── Encoding ─────────────────────────────────────────────────────────
# Ensure native commands (copilot, node) emit and receive UTF-8.
# Without this, Windows mangles π → ╧Ç, — → ΓÇö, etc.
# "We're not in Kansas anymore." — The Wizard of Oz (1939, close enough)
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$OutputEncoding            = [System.Text.Encoding]::UTF8

# ── Paths ────────────────────────────────────────────────────────────
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$ServerJs  = Join-Path $ScriptDir 'server.js'

# Copilot CLI config paths — "These go to eleven." — Spinal Tap (1984)
# Copilot CLI's --config-dir defaults to ~/.copilot on ALL platforms,
# NOT %APPDATA% on Windows. Using the wrong path means copilot never
# sees the installed config — "Nobody puts Baby in the wrong corner."
# — Dirty Dancing (1987)
if ($env:XDG_CONFIG_HOME) {
    $CopilotConfigDir = $env:XDG_CONFIG_HOME
} else {
    $CopilotConfigDir = Join-Path $HOME '.copilot'
}
$McpConfigFile  = Join-Path $CopilotConfigDir 'mcp-config.json'
$McpServerName  = 'hyperlight-sandbox'

# ── Helpers ──────────────────────────────────────────────────────────

function Write-Info  { param([string]$Message) Write-Host "ℹ  $Message" -ForegroundColor Cyan }
function Write-Ok    { param([string]$Message) Write-Host "✅ $Message" -ForegroundColor Green }
function Write-Warn  { param([string]$Message) Write-Host "⚠  $Message" -ForegroundColor Yellow }
function Write-Fail  { param([string]$Message) Write-Host "❌ $Message" -ForegroundColor Red; exit 1 }

function Write-Banner {
    Write-Host ''
    Write-Host '🔒 Hyperlight JS × GitHub Copilot CLI Demo' -ForegroundColor Cyan
    Write-Host ''
}

function Write-Separator {
    Write-Host ''
    Write-Host '────────────────────────────────────────────────────────' -ForegroundColor DarkGray
    Write-Host ''
}

function Get-NowMs {
    [long]([DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds())
}

function Write-Elapsed {
    param([string]$Phase, [long]$StartMs)
    $elapsed = (Get-NowMs) - $StartMs
    $secs    = [math]::Floor($elapsed / 1000)
    $frac    = $elapsed % 1000
    Write-Host ("⏱  {0,-40} {1}.{2:D3}s" -f $Phase, $secs, $frac) -ForegroundColor DarkGray
}

# ── Prerequisite Checks ─────────────────────────────────────────────

function Test-Prerequisites {
    Write-Info 'Checking prerequisites...'

    # Node.js
    $nodeBin = Get-Command node -ErrorAction SilentlyContinue
    if (-not $nodeBin) { Write-Fail 'Node.js is required but not installed. Install from https://nodejs.org' }
    $nodeVersion = & node --version 2>&1
    Write-Ok "Node.js $nodeVersion"

    # Copilot CLI
    $script:CopilotBin = $null
    $copilotCmd = Get-Command copilot -ErrorAction SilentlyContinue
    if ($copilotCmd) {
        $script:CopilotBin = $copilotCmd.Source
    } else {
        # Check typical VS Code Server location (Linux remote / WSL)
        $vscodePath = Join-Path $HOME '.vscode-server/data/User/globalStorage/github.copilot-chat/copilotCli/copilot'
        if (Test-Path $vscodePath) {
            $script:CopilotBin = $vscodePath
        }
        # Check typical Windows location
        if (-not $script:CopilotBin -and ($IsWindows -or $env:OS -match 'Windows')) {
            $winPath = Join-Path $env:LOCALAPPDATA 'Programs\copilot-cli\copilot.exe'
            if (Test-Path $winPath) { $script:CopilotBin = $winPath }
        }
    }
    if (-not $script:CopilotBin) {
        Write-Fail 'GitHub Copilot CLI not found. Install with: npm install -g @github/copilot'
    }
    Write-Ok "Copilot CLI found at: $($script:CopilotBin)"

    # Server script
    if (-not (Test-Path $ServerJs)) { Write-Fail "Server script not found at: $ServerJs" }
    Write-Ok "MCP server: $ServerJs"

    # npm dependencies
    $nodeModules = Join-Path $ScriptDir 'node_modules'
    if (-not (Test-Path $nodeModules)) {
        Write-Warn 'node_modules not found — installing dependencies...'
        # Delegate to cmd.exe to dodge PowerShell's long-standing issues
        # with .cmd shim argument mangling. "Short Circuit" (1986) — we
        # need the real npm, not Johnny 5 having a stroke.
        Push-Location $ScriptDir
        try {
            & cmd /c 'npm install'
            if ($LASTEXITCODE -ne 0) { Write-Fail 'npm install failed' }
        } finally {
            Pop-Location
        }
    }
    Write-Ok 'Dependencies installed'

    # Native addon smoke test — verify the .node binary loads and has
    # the methods we need. The old check started server.js and waited
    # for a banner that never came (stdio transport blocks on connect).
    # This just imports lib.js which validates the native addon at
    # module load time. Instant, reliable, catches the exact failure.
    # "Trust, but verify." — Reagan (1987)
    Write-Info 'Verifying native addon loads correctly...'
    $libJs = Join-Path $ScriptDir '../../lib.js'
    # node --input-type=module so we can use dynamic import() from stdin
    $smokeResult = & node --input-type=module -e "import('file:///' + '$($libJs -replace '\\','/')').then(() => console.log('OK')).catch(e => { console.error(e.message); process.exit(1); })" 2>&1
    if ($LASTEXITCODE -ne 0) {
        $errMsg = ($smokeResult | Out-String).Trim()
        Write-Fail "Native addon failed to load — rebuild with 'just build'.`n$errMsg"
    }
    Write-Ok 'Native addon loads successfully'

    Write-Host ''
}

# ── MCP Config Management ───────────────────────────────────────────

function Build-McpJson {
    <#
    .SYNOPSIS
        Build the JSON MCP config, forwarding sandbox limits + observability
        env vars. Copilot CLI spawns its own server process, so we must
        embed config in the MCP config's "env" field.

        Uses native PowerShell JSON instead of node -e to avoid PS7's
        native-command argument mangling with multi-line strings.
        "Who you gonna call?" — Ghostbusters (1984). ConvertTo-Json.
    .PARAMETER ForInstall
        When set, uses fixed well-known temp paths for HYPERLIGHT_TIMING_LOG
        and HYPERLIGHT_CODE_LOG instead of per-session random paths. This
        lets Copilot spawn the server with predictable log locations.
    #>
    param([switch]$ForInstall)

    $env:HYPERLIGHT_CPU_TIMEOUT_MS  = $CpuTimeout
    $env:HYPERLIGHT_WALL_TIMEOUT_MS = $WallTimeout
    $env:HYPERLIGHT_HEAP_SIZE_MB    = $HeapSize
    $env:HYPERLIGHT_SCRATCH_SIZE_MB   = $ScratchSize

    $config = [ordered]@{
        mcpServers = [ordered]@{
            $McpServerName = (Build-McpServerEntry -ForInstall:$ForInstall)
        }
    }

    ConvertTo-Json $config -Depth 5
}

function Build-McpServerEntry {
    <#
    .SYNOPSIS
        Build a single MCP server entry (type, command, args, env).
        Shared by Build-McpJson (full config) and Install-McpConfig
        (merge into existing config).
    #>
    param([switch]$ForInstall)

    # Build the env block — sandbox limits always included, observability
    # vars only when set AND this is not a permanent install.
    $envHash = [ordered]@{
        HYPERLIGHT_CPU_TIMEOUT_MS  = [string]$CpuTimeout
        HYPERLIGHT_WALL_TIMEOUT_MS = [string]$WallTimeout
        HYPERLIGHT_HEAP_SIZE_MB    = [string]$HeapSize
        HYPERLIGHT_SCRATCH_SIZE_MB   = [string]$ScratchSize
    }

    if ($ForInstall) {
        # Permanent install: include timing log at a fixed well-known path.
        # Code logging is intentionally omitted from permanent installs —
        # it would persist all executed JS to disk by default, which is a
        # privacy concern and can grow unbounded.
        # "Roads? Where we're going, we don't need roads." — Back to the Future (1985)
        $tempDir = [System.IO.Path]::GetTempPath()
        $envHash['HYPERLIGHT_TIMING_LOG'] = (Join-Path $tempDir 'hyperlight-timing.jsonl') -replace '\\', '/'
    } else {
        # Per-session: use the current env vars (random per-session paths
        # set by the script to avoid clobbering between concurrent runs).
        if ($env:HYPERLIGHT_TIMING_LOG) { $envHash['HYPERLIGHT_TIMING_LOG'] = $env:HYPERLIGHT_TIMING_LOG }
        if ($env:HYPERLIGHT_CODE_LOG)   { $envHash['HYPERLIGHT_CODE_LOG']   = $env:HYPERLIGHT_CODE_LOG }
    }

    # Use forward slashes in the server path for JSON portability
    $serverPath = $ServerJs -replace '\\', '/'

    [ordered]@{
        type    = 'stdio'
        command = 'node'
        args    = @($serverPath)
        env     = $envHash
    }
}

function Install-McpConfig {
    Write-Info "Installing MCP server config to $McpConfigFile..."

    if (-not (Test-Path $CopilotConfigDir)) {
        New-Item -ItemType Directory -Path $CopilotConfigDir -Force | Out-Null
    }

    if (Test-Path $McpConfigFile) {
        $existingRaw = Get-Content $McpConfigFile -Raw
        if ($existingRaw -match [regex]::Escape($McpServerName)) {
            Write-Ok "Already configured in $McpConfigFile"
            return
        }

        # Backup existing config
        $backupPath = "$McpConfigFile.bak"
        Copy-Item $McpConfigFile $backupPath
        Write-Warn "Backed up existing config to $backupPath"

        # Merge: add our server to existing config — pure PowerShell,
        # no node -e shenanigans. "Do. Or do not. There is no try."
        # — Yoda, The Empire Strikes Back (1980)
        $existingConfig = $existingRaw | ConvertFrom-Json -AsHashtable
        if (-not $existingConfig.ContainsKey('mcpServers')) {
            $existingConfig['mcpServers'] = @{}
        }
        $existingConfig['mcpServers'][$McpServerName] = Build-McpServerEntry -ForInstall
        $existingConfig | ConvertTo-Json -Depth 5 | Set-Content -Path $McpConfigFile -Encoding utf8NoBOM
    } else {
        Build-McpJson -ForInstall | Set-Content -Path $McpConfigFile -Encoding utf8NoBOM
    }

    Write-Ok "Installed! Config written to $McpConfigFile"
    Write-Host (Get-Content $McpConfigFile -Raw) -ForegroundColor DarkGray
}

function Uninstall-McpConfig {
    if (-not (Test-Path $McpConfigFile)) {
        Write-Warn "No config file found at $McpConfigFile"
        return
    }

    $content = Get-Content $McpConfigFile -Raw
    if ($content -notmatch [regex]::Escape($McpServerName)) {
        Write-Warn "$McpServerName not found in $McpConfigFile"
        return
    }

    # Pure PowerShell JSON manipulation — no node -e needed.
    # "Wax on, wax off." — The Karate Kid (1984)
    $config = $content | ConvertFrom-Json -AsHashtable
    if ($config.ContainsKey('mcpServers')) {
        $config['mcpServers'].Remove($McpServerName)
    }

    if (($config['mcpServers'] ?? @{}).Count -eq 0) {
        Remove-Item $McpConfigFile
        Write-Host 'Config file removed (no servers remaining).'
    } else {
        $config | ConvertTo-Json -Depth 5 | Set-Content -Path $McpConfigFile -Encoding utf8NoBOM
        Write-Host 'Server removed from config.'
    }
    Write-Ok "Uninstalled $McpServerName from Copilot CLI config"
}

function Test-ConfigConflict {
    <#
    .SYNOPSIS
        Warn if a permanent install exists — the script's per-session
        --additional-mcp-config will override it for the duration of
        the session. Same server name = temp config wins via augment
        merge semantics. "Danger, Will Robinson!" — Lost in Space
        (syndicated throughout the 80s)
    #>
    if ((Test-Path $McpConfigFile) -and
        ((Get-Content $McpConfigFile -Raw) -match [regex]::Escape($McpServerName))) {
        Write-Warn "A permanent install of '$McpServerName' exists in $McpConfigFile."
        Write-Warn 'The script''s per-session config (--additional-mcp-config) will override it.'
        Write-Warn 'To use the permanent config directly, just run: copilot'
    }
}

# ── Demo Prompts ─────────────────────────────────────────────────────

# Each entry is @{ Title = '...'; Prompt = '...' }
$DemoPrompts = @(
    @{
        Title  = 'Calculate π to 50 decimal places'
        Prompt = 'Write a function using the Machin formula to calculate π to 50 decimal places. Return the result as a JSON object with the value as a string.'
    }
    @{
        Title  = 'Sieve of Eratosthenes'
        Prompt = 'Find all prime numbers below 10,000 using the Sieve of Eratosthenes. Return JSON with the count and the last 10 primes.'
    }
    @{
        Title  = 'Maze Generation'
        Prompt = 'Generate a random 25×25 maze using recursive backtracking. Return it as ASCII art using # for walls and spaces for paths, plus the dimensions as JSON.'
    }
)

# ── Run Prompt ───────────────────────────────────────────────────────

function Invoke-DemoPrompt {
    <#
    .SYNOPSIS
        Run a single prompt via Copilot CLI programmatic mode.
        Returns $true on success, $false on failure.
    #>
    param(
        [string]$Title,
        [string]$Prompt
    )

    $promptStart = Get-NowMs

    Write-Host "🎯 $Title" -ForegroundColor White
    Write-Host "Prompt: $Prompt" -ForegroundColor DarkGray
    Write-Host "Model:  $Model" -ForegroundColor DarkGray

    # Timing log — the MCP server writes a JSON-lines record here each
    # time execute_javascript is called. Like Knight Rider's KITT
    # dashboard but for sandbox performance.
    # Avoid GetTempFileName() — it creates an orphan .tmp file we'd
    # never clean up. Construct path directly instead.
    $timingLog = Join-Path ([System.IO.Path]::GetTempPath()) "hyperlight-timing-$PID-$(Get-Random).jsonl"
    $env:HYPERLIGHT_TIMING_LOG = $timingLog

    # Code log — the MCP server dumps the received JS source here
    $codeLog = $null
    if ($ShowCode) {
        $codeLog = Join-Path ([System.IO.Path]::GetTempPath()) "hyperlight-code-$PID-$(Get-Random).js"
        $env:HYPERLIGHT_CODE_LOG = $codeLog
    } else {
        Remove-Item Env:\HYPERLIGHT_CODE_LOG -ErrorAction SilentlyContinue
    }

    # Build MCP config to a temp file — utf8NoBOM to avoid confusing
    # copilot CLI's JSON parser with a BOM header.
    $mcpTmp = Join-Path ([System.IO.Path]::GetTempPath()) "hyperlight-mcp-$PID-$(Get-Random).json"
    Build-McpJson | Set-Content -Path $mcpTmp -Encoding utf8NoBOM

    # Structured prompt — steers the agent to call our tool directly.
    # Avoids the "Full Metal Jacket" problem where the agent goes on
    # a recon mission reading every file instead of calling the tool.
    $fullPrompt = @"
TASK: $Prompt

INSTRUCTIONS: You have an MCP tool called 'execute_javascript' from the 'hyperlight-sandbox' server. This tool takes a single parameter 'code' containing JavaScript source code. The code runs in a sandboxed QuickJS engine, NOT Node.js — there is no require(), no fetch(), no fs. The code MUST use 'return <expression>' at the top level to produce output (like a function body). Call the execute_javascript tool with your JavaScript code now. Do NOT read files, start servers, run shell commands, or do anything else. After you receive the tool result, present the answer in ONE short response and STOP. Do NOT attempt any follow-up actions, additional tool calls, or continuation. Your task is complete the moment you present the result.
"@

    # Write the prompt to a temp file and pass via @file to avoid PS7's
    # native-command argument mangling with multi-line here-strings.
    # Emit the command if -ShowCommand was requested.
    # "Show me the money!" — Jerry Maguire (1996... close enough to the 80s)
    if ($ShowCommand) {
        # Copy-pasteable command with the full structured prompt.
        # Omits --additional-mcp-config because the temp file gets
        # cleaned up. Relies on a permanent install.
        $escapedPrompt = $fullPrompt -replace "'", "''"
        $mcpInstalled = (Test-Path $McpConfigFile) -and
            ((Get-Content $McpConfigFile -Raw) -match [regex]::Escape($McpServerName))

        # Build the install command with any non-default sandbox limits
        # so the permanent config gets the same settings.
        # "If you build it, he will come." — Field of Dreams (1989)
        $installFlags = ''
        if ($CpuTimeout  -ne 1000) { $installFlags += " -CpuTimeout $CpuTimeout" }
        if ($WallTimeout -ne 5000) { $installFlags += " -WallTimeout $WallTimeout" }
        if ($HeapSize    -ne 16)   { $installFlags += " -HeapSize $HeapSize" }
        if ($ScratchSize   -ne 1)    { $installFlags += " -ScratchSize $ScratchSize" }

        Write-Host ''
        Write-Host '🔧 Copy-pasteable command:' -ForegroundColor Cyan
        if (-not $mcpInstalled) {
            Write-Host ''
            Write-Host '⚠  The MCP server must be installed before this command will work.' -ForegroundColor Yellow
            Write-Host '  Install it now:' -ForegroundColor Yellow
            Write-Host ''
            Write-Host ("    .\demo-copilot-cli.ps1 -Mode Install{0}" -f $installFlags) -ForegroundColor Yellow
            Write-Host ''
            Write-Host '  To remove it later:' -ForegroundColor Yellow
            Write-Host ''
            Write-Host '    .\demo-copilot-cli.ps1 -Mode Uninstall' -ForegroundColor Yellow
        }
        Write-Host ''
        Write-Host  '  copilot `'
        Write-Host ("    -p '{0}' ``" -f $escapedPrompt)
        Write-Host  '    -s `'
        Write-Host  '    --allow-all-tools `'
        Write-Host  '    --deny-tool shell `'
        Write-Host  '    --deny-tool write `'
        Write-Host  '    --deny-tool read `'
        Write-Host  '    --deny-tool fetch `'
        Write-Host  '    --no-custom-instructions `'
        Write-Host  '    --no-ask-user `'
        Write-Host  '    --disable-builtin-mcps `'
        Write-Host ("    --model {0}" -f $Model)
        Write-Host ''
    }

    # Flags rationale (from `copilot --help`):
    #
    #   --additional-mcp-config @file   Register our MCP server for this session
    #                                   only (no permanent install required).
    #
    #   --allow-all-tools               REQUIRED for -p (non-interactive) mode.
    #                                   Individual --allow-tool patterns only work
    #                                   in interactive mode's permission prompts.
    #                                   See `copilot --help` for details.
    #
    #   --available-tools               Restrict model to ONLY our MCP tool plus
    #                                   internal tools the agent needs to function
    #                                   (task_complete, report_intent). The model
    #                                   cannot call shell, file write, web fetch,
    #                                   or any other tool. This is the security
    #                                   layer — even though --allow-all-tools is
    #                                   set, only whitelisted tools are visible.
    #
    #   --no-custom-instructions        Don't load AGENTS.md / copilot-instructions.md
    #                                   which could confuse the agent.
    #
    #   --no-ask-user                   Don't ask clarifying questions in -p mode.
    #
    #   --disable-builtin-mcps          Don't load the GitHub MCP server — we only
    #                                   want our sandbox.
    #
    #   -p                              Programmatic (non-interactive) mode.
    #
    # Security: use the documented --allow-all-tools + --deny-tool pattern
    # from https://docs.github.com/copilot/concepts/agents/about-copilot-cli
    #
    #   --allow-all-tools : auto-approve all tools (required for -p mode)
    #   --deny-tool 'shell' : BLOCK all shell commands (takes precedence)
    #   --deny-tool 'write' : BLOCK all file write/edit operations
    #   --deny-tool 'read'  : BLOCK file reading (agent should only use our MCP tool)
    #   --deny-tool 'fetch' : BLOCK web/HTTP requests
    #   -s                  : Silent — agent response only, no stats/retry noise
    #
    # --deny-tool takes precedence over --allow-all-tools per the docs.
    # Internal plumbing tools (task_complete, report_intent) are NOT
    # in the shell/write/MCP categories so they remain available.
    # Our MCP tool (hyperlight-sandbox → execute_javascript) is allowed
    # because it's not denied.
    #
    # -s suppresses the agentic loop retry noise ("Continuing autonomously",
    # "Response was interrupted due to a server error") that occurs when
    # the model's continuation turn hits transient API errors after
    # already completing the actual task.
    #
    # We also filter out the "Execution failed" line that leaks through
    # -s when the agentic continuation gives up — the actual task was
    # already successful at that point. The exit code is still 0.
    #
    # Like WarGames taught us: the only winning move is not to grant
    # shell access. — WarGames (1983)
    $copilotStart = Get-NowMs

    try {
        # Use --% (stop-parsing token) to prevent PS from mangling
        # the native command arguments. Pass prompt via temp file.
        $rawOutput = & $script:CopilotBin `
            -p $fullPrompt `
            -s `
            --additional-mcp-config "@$mcpTmp" `
            --allow-all-tools `
            --deny-tool shell `
            --deny-tool write `
            --deny-tool read `
            --deny-tool fetch `
            --no-custom-instructions `
            --no-ask-user `
            --disable-builtin-mcps `
            --model $Model 2>&1

        # Filter output:
        #   1. Drop "Execution failed:" noise from agentic continuation retries
        #   2. Strip leading blank lines the CLI emits while waiting for the
        #      model — keeps blank lines *within* the response body intact.
        #      "Every breath you take, every blank you make…" — The Police (1983)
        $lines = $rawOutput -split "`n" |
            Where-Object { $_ -notmatch '^Execution failed:' }

        # Strip leading blank lines (keep blanks within the body)
        $seenContent = $false
        $filteredLines = @()
        foreach ($line in $lines) {
            if (-not $seenContent -and $line.Trim() -eq '') { continue }
            $seenContent = $true
            $filteredLines += $line
        }

        # Output the response
        $filteredLines | ForEach-Object { Write-Host $_ }
        $success = $true
    }
    catch {
        Write-Warn "Prompt failed (Copilot may not be authenticated or the model may be unavailable)"
        Write-Warn $_.Exception.Message
        $success = $false
    }

    $copilotElapsedMs = (Get-NowMs) - $copilotStart

    # ── Show generated code (if -ShowCode) ───────────────────────
    if ($ShowCode -and $codeLog -and (Test-Path $codeLog) -and (Get-Item $codeLog).Length -gt 0) {
        Write-Host ''
        Write-Host '📝 Generated code:' -ForegroundColor White
        Write-Host '─────────────────────────────────────────────' -ForegroundColor DarkGray
        Get-Content $codeLog | ForEach-Object {
            Write-Host "  $_" -ForegroundColor DarkGray
        }
        Write-Host '─────────────────────────────────────────────' -ForegroundColor DarkGray
    }

    # ── Timing breakdown ─────────────────────────────────────────
    Write-Host ''
    Write-Host '⏱  Timing breakdown:' -ForegroundColor White
    Write-Elapsed 'Copilot CLI (total round-trip)' $copilotStart

    if ((Test-Path $timingLog) -and (Get-Item $timingLog).Length -gt 0) {
        # Parse the last timing record (in case the model called the
        # tool more than once, the last call is the interesting one).
        # Pure PowerShell — no node -e needed. "ConvertFrom-Json is
        # the one who knocks." — adapted from Breaking Bad (close to 80s)
        $lastLine = Get-Content $timingLog -Tail 1
        $timing = $lastLine | ConvertFrom-Json

        $toolTotalMs   = [int]$timing.totalMs
        $toolInitMs    = [int]$timing.initMs
        $toolSetupMs   = [int]$timing.setupMs
        $toolCompileMs = [int]$timing.compileMs
        $toolSnapMs    = [int]$timing.snapshotMs
        $toolExecMs    = [int]$timing.executeMs

        $modelMs = $copilotElapsedMs - $toolTotalMs
        $modelSecs = [math]::Floor($modelMs / 1000)
        $modelFrac = $modelMs % 1000
        $toolSecs  = [math]::Floor($toolTotalMs / 1000)
        $toolFrac  = $toolTotalMs % 1000

        Write-Host ("  🤖 {0,-36} {1}.{2:D3}s  (LLM code generation + response)" -f 'Model', $modelSecs, $modelFrac) -ForegroundColor Cyan
        Write-Host ("  🔧 {0,-36} {1}.{2:D3}s  (MCP tool total)" -f 'Tool execution', $toolSecs, $toolFrac) -ForegroundColor Cyan

        if ($toolInitMs -gt 0) {
            Write-Host ("    ├─ Sandbox init:     {0,5}ms" -f $toolInitMs) -ForegroundColor DarkGray
        }
        Write-Host ("    ├─ Handler setup:    {0,5}ms" -f $toolSetupMs)   -ForegroundColor DarkGray
        Write-Host ("    ├─ Compile & load:   {0,5}ms" -f $toolCompileMs) -ForegroundColor DarkGray
        Write-Host ("    ├─ Snapshot:         {0,5}ms" -f $toolSnapMs)    -ForegroundColor DarkGray
        Write-Host ("    └─ JS execution:     {0,5}ms" -f $toolExecMs)    -ForegroundColor DarkGray
    } else {
        Write-Warn 'No tool timing data — the model may not have called the tool'
    }

    Write-Elapsed "Total for '$Title'" $promptStart

    # Clean up temp files
    Remove-Item $mcpTmp      -ErrorAction SilentlyContinue
    Remove-Item $timingLog   -ErrorAction SilentlyContinue
    if ($codeLog) { Remove-Item $codeLog -ErrorAction SilentlyContinue }

    return $success
}

# ── Main ─────────────────────────────────────────────────────────────

Write-Banner
Write-Info "Using model: $Model"
Write-Info "Sandbox limits: CPU ${CpuTimeout}ms, wall ${WallTimeout}ms, heap ${HeapSize}MB, scratch ${ScratchSize}MB"

switch ($Mode) {
    'Install' {
        Test-Prerequisites
        Install-McpConfig
        Write-Host ''
        Write-Info 'You can now use it in Copilot CLI:'
        Write-Host '  copilot' -ForegroundColor White
        Write-Host '  > Calculate π to 50 decimal places using the Machin formula' -ForegroundColor DarkGray
        exit 0
    }

    'Uninstall' {
        Uninstall-McpConfig
        exit 0
    }

    'Headless' {
        Test-Prerequisites
        Test-ConfigConflict

        # If a custom prompt was given, run just that one and exit.
        # "There can be only one." — Highlander (1986)
        if ($Prompt) {
            Write-Info 'Running custom prompt in headless mode...'
            Write-Separator
            $runStart = Get-NowMs
            $result = Invoke-DemoPrompt -Title 'Custom prompt' -Prompt $Prompt
            Write-Separator
            Write-Elapsed 'Custom prompt' $runStart
            exit ([int](-not $result))
        }

        Write-Info "Running $($DemoPrompts.Count) demo prompts in headless mode..."
        Write-Separator

        $runStart = Get-NowMs
        $passed   = 0
        $failed   = 0

        foreach ($demo in $DemoPrompts) {
            $result = Invoke-DemoPrompt -Title $demo.Title -Prompt $demo.Prompt
            if ($result) { $passed++ } else { $failed++ }
            Write-Separator
        }

        Write-Elapsed "All $($DemoPrompts.Count) prompts" $runStart
        Write-Host ''
        Write-Host "Results: $passed passed" -ForegroundColor Green
        if ($failed -gt 0) {
            Write-Host "         $failed failed" -ForegroundColor Red
        }
        exit $failed
    }

    default {
        # Interactive mode
        Test-Prerequisites
        Test-ConfigConflict

        # Run the custom prompt if one was provided, then exit
        if ($Prompt) {
            Write-Info 'Running your custom prompt...'
            Write-Separator
            Invoke-DemoPrompt -Title 'Custom prompt' -Prompt $Prompt | Out-Null
            Write-Separator
            Write-Info 'Done! "I''ll be back." — The Terminator (1984)'
            exit 0
        }

        Write-Info "This demo will run $($DemoPrompts.Count) prompts through Copilot CLI,"
        Write-Info 'each executing JavaScript inside a Hyperlight sandbox.'
        Write-Host ''
        Write-Info 'The MCP server is configured per-session (no permanent install).'
        Write-Info "To install permanently, run: .\demo-copilot-cli.ps1 -Mode Install"
        Write-Separator

        Write-Host 'Ready to run demos?' -ForegroundColor Yellow
        Read-Host 'Press Enter to continue (or Ctrl+C to cancel)'
        Write-Host ''

        for ($i = 0; $i -lt $DemoPrompts.Count; $i++) {
            $demo = $DemoPrompts[$i]
            Invoke-DemoPrompt -Title $demo.Title -Prompt $demo.Prompt | Out-Null
            Write-Separator

            if ($i + 1 -lt $DemoPrompts.Count) {
                $answer = Read-Host 'Next demo? (Enter to continue, q to quit)'
                if ($answer -eq 'q') {
                    # "I'll be back." — The Terminator (1984)
                    Write-Info 'Thanks for watching! "I''ll be back." — The Terminator (1984)'
                    exit 0
                }
            }
        }

        Write-Host '🎉 All demos complete!' -ForegroundColor Green
        # "That's all, folks!" — Porky Pig (well, 1930s, close enough)
        Write-Host '"That''s all, folks!" — Porky Pig (well, 1930s, close enough)' -ForegroundColor DarkGray
    }
}
